export const SLOTS_GET_REQUEST = "SLOTS_GET_REQUEST"
export const SLOTS_GET_SUCCESS = "SLOTS_GET_SUCCESS"
export const SLOTS_GET_FAIL = "SLOTS_GET_FAIL"

export const BOOKED_SLOT_REQUEST = "BOOKED_SLOT_REQUEST"
export const BOOKED_SLOT_SUCCESS = "BOOKED_SLOT_SUCCESS"
export const BOOKED_SLOT_FAIL = "BOOKED_SLOT_FAIL"